config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tweets#index'
  resources :users, only: [:show, :index]
  resources :tweets do 
    resources :comments, only: :create
    resource :likes, only: [:create, :destroy]
    collection do 
      get :search
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :tweet

  validates :user_id, uniqueness: {
    scope: :tweet_id,
    message: "は同じ投稿に２回以上いいねできません"
  }
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :text, presence: true
  belongs_to :user
  has_many :comments
  has_many :likes, dependent: :destroy

  has_many :liked_users, through: :likes, source: :user

  def liked_by?(current_user)
    likes.find_by(user_id: current_user.id).present?
  end

  after_create do
    # lockメソッドを使う
    if Tweet.lock.where(user_id: self.user_id, text: self.text).count > 1
      raise ActiveRecord::RecordNotUnique.new(self)
    end
  end
  
  def self.search(search)
    return Tweet.all  unless search
    Tweet.where('text LIKE(?)', "%#{search}%")
  end  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets, dependent: :destroy
  has_many :comments
  has_many :likes, dependent: :destroy
  has_many :liked_tweets, through: :likes, source: :tweet
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_paramerers, if: :devise_controller?

  protected
  def configure_permitted_paramerers
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/tweets/#{comment.tweet.id}"
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, tweet_id: params[:tweet_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    # binding.pry
    current_user.likes.create!(tweet_id: params[:tweet_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    current_user.likes.find_by(tweet_id: params[:tweet_id]).destroy!
    redirect_back(fallback_location: root_path)
  end

  
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:edit, :show]
  before_action :movie_to_index , except: [:index, :show, :search]

  def index
    @tweets = Tweet.includes(:user).order("created_at DESC").page(params[:page]).per(2)
  end

  def new
    @tweet = Tweet.new
  end

  def create
    Tweet.create!(tweet_params)
  end

  def show
    @comment = Comment.new
    @comments = @tweet.comments.includes(:user)
  end

  def search
    @tweets = Tweet.search(params[:keyword]).page(params[:page]).per(2)
  end

  def edit
    # @tweet = Tweet.find(params[:id])
  end

  def update
    tweet = Tweet.find(params[:id])
    tweet.update(tweet_params)
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
  end

  private
  def tweet_params
    params.require(:tweet).permit(:image, :text).merge(user_id: current_user.id)
  end

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  def movie_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end
  def show
    # binding.pry
    user = User.find(params[:id])
    @nickname = user.nickname
    @tweets = user.tweets.page(params[:page]).per(1).order("created_at DESC")
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MavicTweet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript">
      WebForbConfig = {
        google: { families: [ 'Unica+One::lation'] }
      };
      (function(){
        var wf = document.createElement('script');
        wf.src = ('https:' == document.location.protocol ? 'https' : 'http') + 
        '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
        wf.type = 'text/javascript';
        wf.async = 'true';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(wf, s);
      })();
    </script>
  </head>

  <body>
    <header class="header">
      <%= render 'shared/header'%>
    </header>
    
    <%= yield %>
    
    <footer>
      <p>
      MavicTweet Silver's kG 2020.
      </p>
    </footer>
  </body>
</html>

app/views/shared/_header.html.erb
<div class="header__bar row">
  <h1 class="grid-6"><a href="/">MavicTweet</a></h1>
  <% if user_signed_in? %>
    <div class="user_nav grid-6">
      <span><%= current_user.nickname %>
        <ul class="user__info">
          <li>
            <%= link_to "マイページ", "/users/#{current_user.id}" %>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, data: { confirm: "ログアウトしますか？" }  %>
          </li>
        </ul>
      </span>
      <%= link_to "投稿する", "/tweets/new", class: "post" %>
    </div>
  <% else %>
    <div class="grid-6">
      <%= link_to "ログイン", new_user_session_path, class: "post" %>
      <%= link_to "新規登録", new_user_registration_path, class: "post" %>
    </div>
  <% end %>
</div>

app/views/tweets/_form.html.erb
<%= form.text_field :image, placeholder: "Image Url" %>
<%= form.text_area :text, placeholder: "text", rows: "10" %>
<%= form.submit "SEND" %>

app/views/tweets/_tweet.html.erb
<div class="content_post" style="background-image: url(<%= tweet.image %>);">
  <div class="more">
    <ul class="more_list">
      <li>
        <%= link_to '詳細', "/tweets/#{tweet.id}", method: :get %>
      </li>
      <% if user_signed_in? && current_user.id == tweet.user_id%>
      <li>
        <%= link_to '編集', "/tweets/#{tweet.id}/edit", method: :get %>
      </li>
      <li>
        <%= link_to '削除', "/tweets/#{tweet.id}", method: :delete, data: { confirm: "本当に記録を削除しますか？" }%>
      </li>
      <% end %>
    </ul>
  </div>
  <%= simple_format(tweet.text) %>
  <span class="name">
    <a href="/users/<%= tweet.user.id %>">
      <span>投稿者</span><%= tweet.user.nickname %>
    </a>
  </span>
</div>

app/views/tweets/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      投稿が完了しました。
    </h3>
    <a class="btn" href="/tweets">投稿一覧へ戻る</a>
  </div>
</div>

app/views/tweets/destroy.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      削除が完了しました。
    </h3>
    <a class="btn" href="/">一覧へ戻る</a>
  </div>
</div>

app/views/tweets/edit.html.erb
<div class="contents row">
  <div class="container">
    <%= form_with(model: @tweet, local: true) do |form| %>
      <h3>
        編集する
      </h3>
      <%= render partial: "form", locals: {form: form}%>
    <% end %>
  </div>
</div>

app/views/tweets/index.html.erb
<div class="top text-center"></div>
<%= form_with(url: search_tweets_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>
<div class="contents row">
  <% @tweets.each do |tweet| %>
    <%= render partial: "tweet", locals: { tweet: tweet } %>
  <% end %>
  <%= paginate(@tweets)%>
</div>

app/views/tweets/new.html.erb
<div class="contents row">
  <div class="container">
    <%= form_with(model: @tweet, local: true) do |form| %>
      <h3>
      投稿する
      </h3>
      <%= render partial: "form", locals: {form: form} %>
    <% end %>
  </div>
</div>

app/views/tweets/search.html.erb
<%= form_with(url: search_tweets_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>
<div class="contents row">
  <% @tweets.each do |tweet| %>
    <%= render partial: "tweet", locals: { tweet: tweet} %>
  <% end %>
  <%= paginate(@tweets)%>
</div>

app/views/tweets/show.html.erb
<h1>投稿詳細</h1>
<p>【メールアドレス】 <%= @tweet.user.email %></p>
<p>【内容】 <%= @tweet.text %></p>
<p>【作成日時】 <%= @tweet.created_at %></p>
  <% if @tweet.liked_by?(current_user) %>
    <%# 「いいね！」済みを解除する %>
    <%= link_to "★",  tweet_likes_path(@tweet) ,method: :delete %>
    
  <% else %>
    <%= link_to "☆", tweet_likes_path(@tweet), method: :post %>
    <%# 「いいね」していない（クリックすると「いいね！」にする) %>
    
  <% end %>
</p>

<div class="contents row">
  <div class="content_post" style="background-image: url(<%= @tweet.image %>);">
  <% if user_signed_in? && current_user.id == @tweet.user_id %>
    <div class="more">
      <span><%= image_tag 'arrow_top.png'%></span>
      <ul class="more_list">
        <li>
          <%= link_to '編集', "/tweets/#{@tweet.id}/edit", method: :get %>
        </li>
        <li>
          <%= link_to '削除', "/tweets/#{@tweet.id}", method: :delete, data: { confirm: "本当に記録を削除しますか？" } %>
        </li>
      </ul>
    </div>
  <% end %>
    <%= simple_format(@tweet.text) %>
    <span class="name">
      <a href="/users/<%= @tweet.user.id %>">
        <span>投稿者</span><%= @tweet.user.nickname %>
      </a>
    </span>
  </div>
  <div class="container">
    <% if current_user %>
      <%= form_with(model: [@tweet, @comment], local: true) do |form| %>
        <%= form.text_area :text, placeholder: "コメントする", rows: "2" %>
        <%= form.submit "SEND" %>
      <% end %>
    <% else %>
      <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
    <% end %>

    <div class="comments">
      <h4>コメント一覧</h4>
      <% if @comments %>
        <% @comments.each do |comment| %>
          <p>
            <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>:</strong>
            <%= comment.text %>
          </p>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/tweets/update.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      更新が完了しました
    </h3>
    <a class="btn" href="/">一覧へ戻る</a>
  </div>
</div>

app/views/users/show.html.erb
<div class="contents row">
  <p><%= @nickname %>さんの投稿一覧</p>

  <% @tweets.each do |tweet| %>
    <%= render partial: "tweets/tweet", locals: {tweet: tweet } %>
  <% end %>
  <%= paginate(@tweets)%>
</div>